imu:
  accelerometer:
    sensitive: 4.0
peripherals:
  pwm:
    PWM1:
      type: motor
      index: 0
      protocol: PWM
      rate: 400
    PWM3:
      type: elevator
    PWM4:
      type: aileron-right
    PWM5:
      type: aileron-left
    PWM6:
      type: rudder
