[memory]
ram = { size = "64K", origin = 0x10000000 }
flash = { size = "1M", origin = 0x08000000 }
heap = { size = "128K", origin = 0x20000000 }

[text]
start = 0x08010000

[heap.main]
size = "0"
pools = []

[heap.secondary]
origin = 0x20000000
size = "128K"
pools = [
    { block = "32", capacity = 256 },
    { block = "256", capacity = 96 },
    { block = "512", capacity = 48 },
    { block = "1024", capacity = 24 },
    { block = "2048", capacity = 8 },
    { block = "4096", capacity = 4 },
    { block = "8192", capacity = 2 },
]

[linker]
platform = "arm"
