[package]
authors = ["qiuchengxuan <qiuchengxuan@gmail.com>"]
edition = "2018"
readme = "README.md"
name = "hal"
version = "0.0.1"

[dependencies]
chrono = { version = "0.4", default-features = false }

[lib]
name = "hal"
test = false
bench = false
