kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: submodule
    commands:
      - git submodule update --init --recursive
  - name: codestyle
    commands:
      - export HOME=$DRONE_CI_HOME
      - export PATH=$DRONE_CI_HOME/.cargo/bin:$PATH
      - rustup default nightly
      - git diff-tree --no-commit-id --name-only --diff-filter=AM -r HEAD | grep '\.rs$' | xargs -i rustfmt --edition 2018 --check {}
  - name: build
    commands:
      - export HOME=$DRONE_CI_HOME
      - export PATH=$DRONE_CI_HOME/.cargo/bin:$PATH
      - cargo test
      - cargo build --release
