kind: pipeline
type: kubernetes
name: default
steps:
  - name: codestyle
    image: rust:latest
    commands:
      - git diff-tree --no-commit-id --name-only --diff-filter=AM -r HEAD | grep '\.rs$' | xargs -i rustfmt --edition 2021 --check {}
  - name: cargo-check
    image: rust:latest
    commands:
      - cargo check
    environment:
      CARGO_HOME: /cargo
    volumes:
      - name: cargo
        path: /cargo
volumes:
  - name: cargo
    claim:
      name: drone-ci-cargo
      read_only: false
