[tasks.build]
command = "cargo"
args= [
    "build",
    "--release"
]

[tasks.bin]
command = "arm-none-eabi-objcopy"
args = [
    "-O", "binary",
    "target/thumbv7em-none-eabi/release/omnibusf4",
    "omnibusf4.bin",
]
dependencies = ["build"]
