[tasks.omnibusf4sd-elf]
script = [
'''
#!/usr/bin/env bash
cd boards/omnibusf4sd
cargo build --release
cd -
'''
]

[tasks.omnibusf4sd]
command = "arm-none-eabi-objcopy"
args = [
    "-O", "binary",
    "boards/omnibusf4sd/target/thumbv7em-none-eabi/release/omnibusf4sd",
    "omnibusf4sd.bin",
]
dependencies = ["omnibusf4sd-elf"]
