[tasks.omnibusf4sd-elf]
command = "cargo"
args= [
    "build",
    "--release",
    "--manifest-path",
    "boards/omnibusf4sd/Cargo.toml"
]

[tasks.omnibusf4sd]
command = "arm-none-eabi-objcopy"
args = [
    "-O", "binary",
    "boards/omnibusf4sd/target/thumbv7em-none-eabi/release/omnibusf4sd",
    "omnibusf4sd.bin",
]
dependencies = ["omnibusf4sd-elf"]
