[package]
authors = ["qiuchengxuan <qiuchengxuan@gmail.com>"]
edition = "2018"
readme = "README.md"
name = "chips"
version = "0.0.1"

[dependencies]
cortex-m = "0.6"
cortex-m-rt = "0.6"
crc = { version = "1.8", default-features = false }
stm32f4xx-hal = { git = "https://github.com/stm32-rs/stm32f4xx-hal", optional = true }

[lib]
name = "chips"
test = false
bench = false
