[package]
authors = ["qiuchengxuan <qiuchengxuan@gmail.com>"]
edition = "2018"
readme = "README.md"
name = "chips"
version = "0.0.1"

[dependencies]
cortex-m = "0.6"
cortex-m-rt = "0.6"
stm32f4xx-hal = { version = "0.8", features = ["stm32f405", "rt", "usb_fs"] }

[lib]
name = "chips"
test = false
bench = false
